services:
  faceage:
    image: rkhafizov.faceage_image
    build:
      context: .
      dockerfile: Dockerfile
      # args:                
      #   UID: ${UID}        
      #   GID: ${GID}        

    container_name: rkhafizov.faceage_container
    # user: "${UID}:${GID}"
    network_mode: host
    ipc: host
    mem_limit: 200g
    volumes:
      - /home/r.khafizov/faceage/faceage_mri:/workspace/faceage_mri
      - /mnt/data/r.khafizov:/workspace/data
      # - /mnt/data/r.khafizov1:/workspace/data
    ports:
      - "6666:6666"  # Adjust the port mapping as needed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Adjust GPU visibility as needed
      - NCCL_SOCKET_IFNAME=eno1
      - MASTER_ADDR=127.0.0.1            # single-node: use loopback for coordination
      - MASTER_PORT=12345                # or any free port
    command: "/bin/bash -c 'source /etc/bash.bashrc && tail -f /dev/null && /bin/bash'"  # Keep container running
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # count: 1
            device_ids: ["0,1,2"]
            capabilities: [gpu]
        limits:
          memory: 200G